### ISSUE TITLE
docs: insufficient description of params

### ISSUE THREAD

**Issue by skshetry** [iterative/dvc.org#1683]
https://github.com/iterative/dvc.org/blob/7546c1f45a435ebd7840426a9349c402e72bace1/content/docs/user-guide/dvc-files-and-directories.md#L153-L155

The link to _parameter dependencies_ takes to the `params` where it's not clear where I find what it means (unless I read 341 words, who has time for it).

Also, the meaning of  _key paths_ is not clear, and makes it even more confusing since it talks about "referring to a ... file".

It also does not mention any way to specify a custom params file.

Discord Context: https://discord.com/channels/485586884165107732/563406153334128681/741913494991142932

**Comment by shcheklein** [comment]
Agreed, sentence is very confusing - it should be plain and explicit. I guess it comes from the fact that this doc initially was initially written as a reference for `.dvc` files, that were not human editable in its default mode. With 1.0 we have moved to some DVC language in "dvc.yaml", but haven't optimized docs for this.

I would suggest to do initial simple change though - one or two sentences to be more explicit. Ideally that should be enough.

**Comment by jorgeorpinel** [comment]
I agree that the text can be improved, but for context, we are talking about a bullet under "Each stage can contain the possible following fields:" in https://dvc.org/doc/user-guide/dvc-files-and-directories#dvcyaml-file. The goal here is to describe the fields inside dvc.yaml stages and what format they may have.

> link to params where it's not clear where I find what it means

Idk. https://dvc.org/doc/command-reference/params starts it's **Description** with

> In order to track parameters and hyperparameters associated to machine learning experiments in DVC projects, DVC provides a different type of dependencies: parameters.

**Comment by jorgeorpinel** [comment]
p.s. this is why we need a **DVC Concepts** guide (being worked on) and extract all these explanations from the cmd ref though (e.g. params, metrics, remote, etc.)

**Comment by shcheklein** [comment]
Glossary can definitely help here I think. Short explicit description in the tooltip should be enough. + a link to the long params command reference. Text should be fixed first though. One sentence change in this case can solve 80% of the problem.

**Comment by jorgeorpinel** [comment]
OK. See https://github.com/iterative/dvc.org/pull/1680/commits/6649f0a858be8f7f88123f373556bb50657c15da

**Comment by skshetry** [comment]
@jorgeorpinel, the dvc.yaml docs should be a guide rather than the reference. As it is, it's hard to translate that reference into a hand-written dvc.yaml file.

Just for params, it does not answer many of the questions which are essential to write a dvc.yaml stage (even in the new edition), such as:

1. What is a parameter dependency?
2. How do I track specific params?
1. How to track nested values of params?
2. How to use it for custom params file?

**Comment by jorgeorpinel** [comment]
Maybe we need a separate guide, but this one doc is more of a reference indeed. Even if it's in the User Guide section. For now it's being solved in the commit I mentioned, please check out that PR.

Can you think of more questions you think are not answered by the doc? Please list them all and we'll open a separate issue to discuss. In fact maybe if you can move all of them to another issue that's be great. 

The Azure schema page seems like a huge reference too BTW, not much of a guide.

**Comment by skshetry** [comment]
I don't think the #1680 solves anything. There's glossary for sure, but that does not help anyone to write a dvc.yaml. Not to add, it still does not mention anything about custom params file (which people are finding confusing). 

> The Azure schema page seems like a huge reference too BTW, not much of a guide.

Yeah, it's a reference. But we could do something like that in a guide format, i.e having separate sections of params/deps/outs/plots and providing a few examples of each.

I'm re-opening this.

**Comment by shcheklein** [comment]
@skshetry I agree with Jorge on this. The title says "insufficient description of params". We have more than enough to my mind. 

> Yeah, it's a reference. But we could do something like that in a guide format, i.e having separate sections of params/deps/outs/plots and providing a few examples of each.

> There's glossary for sure, but that does not help anyone to write a dvc.yaml

both problems are related but way more global than this ticket (again, see the title). Let's create a separate issue for writing the `dvc yaml` guide. Eventually it might turn out that section will replace this single document, for example. But description of the ticket and the title are misleading and narrow.

**Comment by skshetry** [comment]
"insufficient description" is a vague term, so it depends on how you see it. It still leaves some question unanswered:

> 2. How do I track specific params?
> 3. How to track nested values of params?
> 4. How to use it for custom params file?

These are "how-to" but could have been mentioned on the reference, but, anyway if we go the dvcyaml-guide route, I'm fine with closing this for the exchange of the other issue.

**Comment by arbazz03** [comment]
tk
